classdef RealTurbojet
    properties (Access = public)
        Inputs = struct()
        Outputs = struct()
    end
    
    methods
        function obj = RealTurbojet(mach,flightRegimeType,flightRegimeValue,gammaC,cpC,hpr,Tt4,cpT,gammaT,P0P9,piC,piDmax,piB,piN,polyEffC,polyEffT,etaB,etaM,afterburner,Tt7,cpAB,gammaAB,piAB,etaAB)
            % Construct an instance of this class with engine inputs
            if nargin > 0
                obj.Inputs = struct('mach', mach,...
                    'flightRegimeType', flightRegimeType,...
                    'flightRegimeValue', flightRegimeValue,...
                    'gammaC', gammaC,...
                    'cpC', cpC,...
                    'hpr', hpr,...
                    'Tt4', Tt4,...
                    'cpT', cpT,...
                    'gammaT', gammaT,...
                    'P0P9', P0P9,...
                    'piC', piC,...
                    'piDmax', piDmax,...
                    'piB', piB,...
                    'piN', piN,...
                    'eC', polyEffC,...
                    'eT', polyEffT,...
                    'etaB', etaB,...
                    'etaM', etaM,...
                    'afterburner', afterburner,...
                    'Tt7', Tt7,...
                    'cpAB', cpAB,...
                    'gammaAB', gammaAB,...
                    'piAB', piAB,...
                    'etaAB', etaAB);
            else
                obj.Inputs = struct();
            end
        end
        
        function obj = set.Inputs(obj, inputStruct)
            % Set the inputs struct
            obj.Inputs = inputStruct;
        end
        
        function obj = set.Outputs(obj, outputStruct)
            % Set the outputs struct
            obj.Outputs = outputStruct;
        end
    end
end

