function RunIdealTurbojetAnalysis(app)
% Function that runs when ideal turbojet is selected

% Get the field values
mach = app.ITj_MachNumberEditField.Value;
gammaC = app.ITj_GammaCEditField.Value;
cpC = app.ITj_CpcEditField.Value;
hpr = app.ITj_HprEditField.Value;
Tt4 = app.ITj_Tt4EditField.Value;
FR_value = app.ITj_FlightRegimeEditField.Value;
TempCheckbox = app.ITj_TemperatureCheckbox.Value;
AltCheckbox = app.ITj_AltitudeCheckbox.Value;
piC = app.ITj_PiCEditField.Value;
afterburner = app.ITj_AfterburnerCheckbox.Value;
Tt7 = app.ITj_Tt7EditField.Value;

% Input Validation
validated_mach = ValidateInputsArray(mach, 'Mach', 'Ideal Turbojet');
validated_Tt4 = ValidateInputsArray(Tt4, 'Tt4', 'Ideal Turbojet');
validated_FR_value = ValidateInputsArray(FR_value, 'FlightRegimeValue', 'Ideal Turbojet');

% Conversion to the IS units
converted_cpC = cpC*1000;
converted_hpr = hpr*1000;

% Flight Regime Type Check
if (TempCheckbox && ~AltCheckbox)
    flightRegimeType = FlightRegimeInputType.Temperature;
elseif (~TempCheckbox && AltCheckbox)
    flightRegimeType = FlightRegimeInputType.Altitude;
else
    errordlg("Selecione um regime de voo válido", "Erro na seleção do regime de voo de Turbojet Ideal")
end

% Class assignment
idealTurbojet = IdealTurbojet(validated_mach,...
    flightRegimeType,...
    validated_FR_value,...
    gammaC,...
    converted_cpC,...
    converted_hpr,...
    validated_Tt4,...
    piC,...
    afterburner,...
    Tt7);

% Run Analysis
Tt4_cellArray = num2cell(validated_Tt4);


for i = 1:length(Tt4_cellArray)
    currentTt4 = strcat('T', strrep(num2str(Tt4_cellArray{i}), '.', '_'), 'K');
    if (afterburner)
        [turbojet] = IdealTurbojetAnalysis(validated_mach, ...
            flightRegimeType,...
            validated_FR_value,...
            gammaC,...
            converted_cpC,...
            converted_hpr,...
            validated_Tt4(i),...
            piC,...
            afterburner,...
            Tt7);
    else
        [turbojet] = IdealTurbojetAnalysis(validated_mach, ...
            flightRegimeType,...
            validated_FR_value,...
            gammaC,...
            converted_cpC,...
            converted_hpr,...
            validated_Tt4(i),...
            piC);
    end
    idealTurbojet.Outputs.(currentTt4) = turbojet;
end

app.idealTurbojetEngine = idealTurbojet;

end

